name: Cosma Graph Generation
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - run: npm run cosma-convert
      - run: npm install @graphlab-fr/cosma -g
      - run: cosma modelize
      - run: rm -r ./src/content/blog_temp

      

